### ISSUE TITLE
Download failed notificaion on Plugin installer

### ISSUE THREAD

**Issue by Naab25** [Grammernatzi/XIVComboPlugin#100]
This always appears when I go check the plugins in Dalamud
and I cannot find the plugin in the All Plugin Section coz of it
![image](https://user-images.githubusercontent.com/6531526/159147009-f8cd0a52-b353-479f-99d6-f932d0aa9d5c.png)

**Comment by Grammernatzi** [comment]
Nothing changed and the URL still links properly for me. Can someone else confirm if they are also having this problem?

**Comment by Naab25** [comment]
> Nothing changed and the URL still links properly for me. Can someone else confirm if they are also having this problem?

Found the issue on my end its my IP country address from the Philippines , used a VPN its fine now probably some issue updating the plugin via IP from my country/region
