### ISSUE TITLE
Play to Astrodyne not working

### ISSUE THREAD

**Issue by 542673** [Grammernatzi/XIVComboPlugin#103]
draw on play works perfectly but astrodyne doesnt appear at all when 3 seals are gained

**Comment by Grammernatzi** [comment]
The gauge is likely broken, I noticed this wasn't working either. Not much I can do about it, Dalamud's still WIP after all.

**Comment by Grammernatzi** [comment]
Should be fixed now.

**Comment by 542673** [comment]
it does work now, however astrodyne gets changed back to draw/play while casting (not an issue during lightspeed as everything is instantcast), not sure if its intentional but it wasnt like this on the previous versions

**Comment by Grammernatzi** [comment]
The gaugee is broken, so I am using a check to see if astrodyne is grayed
out or not instead. Casting grays it out, however it disappearing is purely
cosmetic and it won't affect gameplay.
