### ISSUE TITLE
Toxicon being prioritized when it's not available in synced content. 

### ISSUE THREAD

**Issue by Emikzen** [Grammernatzi/XIVComboPlugin#105]
I currently have these 2 settings enabled

![image](https://user-images.githubusercontent.com/50278938/163890260-a115d391-b671-4ec9-809d-0730b69c9ad1.png)

When doing lower level content where Toxicon is not unlocked it still swaps to it making me unable to use Dyskrasia entirely. It does work fine in higher level content where Toxicon is unlocked however and swaps to Dyskrasia when all charges are out(as it should). Don't remember this being an issue pre-6.1 but I could be wrong.

**Comment by Grammernatzi** [comment]
I believe I did specifically fix this recently; are you sure you're using this specific fork? I tested it out myself with level sync and it seems to be working fine.

**Comment by Grammernatzi** [comment]
I can't seem to replicate this and I haven't gotten a response, so I'm just going to close for now. If you continue to have issues with this specific fork, let me know.
