### ISSUE TITLE
Request - Scholar: Adloquium ->Physick when synced

### ISSUE THREAD

**Issue by ratheralarming** [Grammernatzi/XIVComboPlugin#106]
I loveeee the option you have for whm/ast to sync cure 2/benefic 2 when below level 30, and i'd love to have it on scholar for similar reasons. regardless of the answer, tysm for this wonderful fork! i've tried a lot and this is my preferred :)

**Comment by Grammernatzi** [comment]
Probably worth adding, fair enough, since Physick is barely used, if ever, at higher levels. I'll add it later.

**Comment by ratheralarming** [comment]
Thank you so much, you rule! :D

**Comment by Grammernatzi** [comment]
Added and will be updated with the 6.11 patch.
