### ISSUE TITLE
BLM Blizzard 1/3

### ISSUE THREAD

**Issue by Nypheena** [Grammernatzi/XIVComboPlugin#107]
was wondering if it could be a possibility to make it when you're in Umbral ice 3 that it swaps back to blizz 1, mainly this is for lower level content such as MSQ roulette since when you're 50 you don't have enochian and you can't use blizz 3 as filler to get your last mp tick as the cast time is too long so it would be really beneficial for it to swap to blizz 1 in that situation so you can do a filler cast to then go back to fire with full MP

**Comment by Grammernatzi** [comment]
I can go ahead and add this as an option later, seems reasonable.

**Comment by Nypheena** [comment]
thank you very much I appreciate it

**Comment by Grammernatzi** [comment]
Added
