### ISSUE TITLE
Combo descriptions need to overflow off-screen text into separate lines

### ISSUE THREAD

**Issue by SashaFFXIV** [Grammernatzi/XIVComboPlugin#109]
![Wide Window](https://user-images.githubusercontent.com/55117631/169640555-a340ed1a-b3a9-4207-89f4-599d162419aa.png)

![Thin Window](https://user-images.githubusercontent.com/55117631/169640567-f04c9d02-ff62-4a96-8c01-3a260fea5311.png)

Long descriptions are currently unreadable because they flow off-screen.

**Comment by Grammernatzi** [comment]
When I get back to the game in 6.15, I will give it a look. I might be able to wrap the text if Dalamud supports it.

**Comment by Grammernatzi** [comment]
Will be fixed with next push.
