### ISSUE TITLE
Feature request: condensed enhanced gibbets/gallows

### ISSUE THREAD

**Issue by ratheralarming** [Grammernatzi/XIVComboPlugin#113]
Hello again!

I really love the Stalking and Swathing Feature and how it changes Gibbet and Gallows into the enhanced version of the other. However, I would like to give that combo a single button, so that I can have vanilla Guillotine available on another. (I separate my bars between having single target on one row, and aoe on another.)

Hopefully the way I described it makes sense. Thank you very much again for your version of the plugin either way!

**Comment by Grammernatzi** [comment]
Are you saying you want to feature that doesn't change swathe into guillotine? Just trying to make sure, I'm not entirely sure if that's what you want here. Could you not just use the feature that turns your main combo actions into gibbet and gallows? That one doesn't affect Guillotine.

**Comment by ratheralarming** [comment]
Not quite-- my apologies for being unclear!

![image](https://user-images.githubusercontent.com/155172/174330628-47bbcb2e-4421-42d1-a71d-720f02c5861e.png)

I was hoping to have only gibbet/gallows alternate between which is enhanced on a separate single button like this, sort of like the gauss round/ricochet option.

However, I totally understand if you think it's redundant, and can use the feature you're talking about :D

**Comment by Grammernatzi** [comment]
Oh, I see now, I can easily add that, and will do so

**Comment by ratheralarming** [comment]
thank you!! you're the best :D!!!!!

**Comment by Grammernatzi** [comment]
Pushed in 8bdaac1
