### ISSUE TITLE
Feature request - SAM

### ISSUE THREAD

**Issue by faultlline** [Grammernatzi/XIVComboPlugin#114]
Can you add an option to Ikishoten Namikiri Feature to not turn into Shoha if meditation is 3? Sometimes using Shoha after the cast for Ogi clips Kaeshi on my ping
![image](https://user-images.githubusercontent.com/97929169/179748946-cd8cd24f-7fb1-4a0f-94e0-fec2d84f4789.png)

**Comment by Grammernatzi** [comment]
This should already be a thing, do you have Ogi-Namikiri to Shoha enabled? Just turn it off

**Comment by faultlline** [comment]
Nope, tested with only this option enabled and it turns into Shoha only if the 3rd meditation stack comes from Ogi. It works as usual if it comes from anywhere else

**Comment by Grammernatzi** [comment]
I just looked at it, and yes, there is a bug where it doesn't check, I will add the check; it should work fine after. Just give me an hour or so.

**Comment by Grammernatzi** [comment]
Should be fixed but I cannot test right now (currently unsubbed), so let me know if it works.

**Comment by faultlline** [comment]
perfect, thank you very much
