### ISSUE TITLE
It works (maybe)

### ISSUE THREAD

**Issue by Grammernatzi** [Grammernatzi/XIVComboPlugin#116]
~~New update broke the plugin, naturally. Will try to get it fixed ASAP, it also depends on how quickly Dalamud gets updated.~~

It works now. May be buggy.

**Comment by Grammernatzi** [comment]
It's worth noting that it seems that this is the big .NET 6 upgrade for Dalamud, as well. So updating may take more time than usual. I'll have to see, once a proper staging build releases.

**Comment by xMovingTargetx** [comment]
Awesome cant wait. Running regular combo atm, but it doesnt get the job done as well as yours. And all my bars are completely outta whack rn :D

**Comment by Grammernatzi** [comment]
Should be working now, from what I can tell. It's a pre-release version, so some stuff may be broken.

**Comment by xMovingTargetx** [comment]
I just downloaded it, trying it now.
