### ISSUE TITLE
Issue with Confiteor Feature combined with Requiescat Confiteor for Paladin

### ISSUE THREAD

**Issue by Ryzison** [Grammernatzi/XIVComboPlugin#120]
[
![image](https://user-images.githubusercontent.com/20791988/190289115-7d7c1cfa-f0d2-44bd-9ac5-4a79368f5389.png)
](https://i.imgur.com/LoKSs6x.png)

Ever since Tuesday's patch, 9/14/2022, upon casting Requiescat it no longer knows when only one stack is remaining, so it starts the Confiteor chain immediately, at 5 stacks.

**Comment by Grammernatzi** [comment]
This is likely an issue with Dalamud's buff tracking, as it uses that system to see what stacks are available. It is something they would have to fix on their end. It frequently likes to break on updates.

**Comment by Grammernatzi** [comment]
I just tested this myself and I can't replicate it. Can anyone else confirm if it happens on their end, too?

**Comment by Ryzison** [comment]
Oh you know, you're right, it does work as intended, Maybe it was this one? 
[https://i.imgur.com/5Orh0Rf.png](https://i.imgur.com/5Orh0Rf.png)
Where Requiescat would be replaced by Holy Spirit, and then at 1 stack it would swap to the Confiteor chain, it's not doing that anymore.

**Comment by Grammernatzi** [comment]
That image is not from my fork of the plugin; the description and name of
the feature is different. You will have to bring it up with the person who
manages that fork.

**Comment by Grammernatzi** [comment]
That's a different feature entirely. That's the one that originally comes from XIVCombo; I got confused and thought it was something else. The Confiteor Feature is the one that should do it, but it works as intended, and I had other people test it after yu mentioned. Are you sure you are using this fork, and the latest version of Dalamud?

**Comment by Ryzison** [comment]
This is where I was taken when I clicked the link provided within the plugin, "XIVComboPlugin Expandedest". before Tuesday I had it set up so that when I cast Requiescat it is then replaced with Holy Spirit, and then at 1 stack it swapped to the Confiteor chain. It no longer does that, Instead, now, after casting Requiescat it is replaced with Confiteor and its chain.

**Comment by Grammernatzi** [comment]
Oh, Requiescat never gets replaced with Holy Spirit. I don't think it was ever supposed to be replaced by it, either? I'd prefer to keep it just Confiteor since sometimes you need to use Confiteor early.
