### ISSUE TITLE
Bug: Flourish does not change to FD4 properly

### ISSUE THREAD

**Issue by citrouille** [Grammernatzi/XIVComboPlugin#121]
I started using this plugin instead of XIVCombo yesterday, but I noticed that Flourish does not change to FD4 as it should until I've used my FD3 proc. I would like to be able to decide which proc to use independently, and I believe the plugin provides the option to, but it doesn't seem to work as advertised. 

https://i.imgur.com/brRgXJP.png with these settings still forces FD3 onto Flourish even though it's not enabled.

**Comment by Grammernatzi** [comment]
Yep, I had this mentioned as well. It's a coding bug. It's been there since
I implemented the feature, I've just been busy with savage/extremes and
everyone who reported it considered it rather minor. I can fix it up ASAP
if it's a problem, it's one line of code.

**Comment by citrouille** [comment]
Thank you for the explanation. Well, I am not really in too much of a hurry, so please go ahead and take your time.

**Comment by Grammernatzi** [comment]
No prob; once things slow down I was going to add a bulk patch of miscellaneous things.

**Comment by Grammernatzi** [comment]
Fixed in latest version
