### ISSUE TITLE
MCH Feature Request

### ISSUE THREAD

**Issue by faultlline** [Grammernatzi/XIVComboPlugin#122]
Can you add an option to replace Drill with Bioblaster if the last action was Spread Shot/Scattergun/Auto Crossbow? Thanks in advance

**Comment by Grammernatzi** [comment]
Sure, that sounds fine. I should also probably add a clause to not do it
while reassemble is active. I'll add it with the next batch of features
that I have planned.

**Comment by Grammernatzi** [comment]
Added in newest version
