### ISSUE TITLE
Reaper: Slice/Spinning Scythe wrongly getting changed into Communio.

### ISSUE THREAD

**Issue by SirBenvil** [Grammernatzi/XIVComboPlugin#123]
The "Combo Communio Feature" (#195) states it's suppose to only replace Gibbet/Gallows/Guillotine. However, it's also changing the Slice/Spinning Scythe combos into Communio. Not only that, but the Slice/Spin Scythe change happens too early; it triggers when you can still cast one more Lemure's Slice/Scythe, so if you misclick you'll lose your last 2 void shroud stacks.

This bug happens regardless of what other features you have enabled. I don't have "Gibbets and Gallows Feature" (#192) enabled, which would change Slice change into Gibbet/Gallows, and then into Communio.

![image](https://user-images.githubusercontent.com/39379389/191064869-2fc4afb5-ad7b-42ed-9e1e-940a6b89ff61.png)

This feature should just do as  the description states, sticking only to Gibbet/Gallows/Guillotine, possibly with an optional child to instead replace Slice/Scythe combo should anyone want that (I imagine most would just want it to stick to Gibbet/Gallows/Guillotine only).

**Comment by Grammernatzi** [comment]
> Not only that, but the Slice/Spin Scythe change happens too early; it triggers when you can still cast one more Lemure's Slice/Scythe, so if you misclick you'll lose your last 2 void shroud stacks.

This is intended unless you also activate the feature for that as well. The idea is that the buttons can either be separate or not depending on the player choice. I prefer this, myself.

Anyway, yes, that was an error with me not checking if the Gibbets and Gallows Feature was enabled for the Slice combo. I do doubt anyone would want Communio to replace the Slice combo if they don't have Gibbets and Gallows Feature enabled, and the same with the Spinning Scythe combo and the Guillotine feature. I fixed it up in a few seconds, I'll be pushing the fix now.
