### ISSUE TITLE
Request: DNC Combos without procs

### ISSUE THREAD

**Issue by eldornoftw** [Grammernatzi/XIVComboPlugin#124]
Heya; Would it please be possible to add 2 options for DNC that are the simple Cascade > Fountain, and Windmill > Bladeshower combos? I'd like to keep the procs as separate buttons so it's a little more complex than the 1-2 button rotations that the Multibutton and "to Procs" options provide (plus it would give more buttons to assign dance steps to using the Dance Step Feature).

If that is possible, I would appreciate it 🙏

**Comment by Grammernatzi** [comment]
Would you also like an option for the procs to combo with each other? Or should I just have them be separate? Either way, I can definitely add this as an option for the combos.

**Comment by eldornoftw** [comment]
Awesome, tysm! 💯
As for the option for procs to combo - I probably wouldn't use that, no, but I guess other people might like it? It's always nice to have options ^^

**Comment by Grammernatzi** [comment]
Yeah, fair; I'll probably add both, then

**Comment by eldornoftw** [comment]
Cool cool, thank you ^^

**Comment by Grammernatzi** [comment]
Done, took the time to do a few things on Dancer overall, as well.
