### ISSUE TITLE
CTD with hotfix

### ISSUE THREAD

**Issue by Lockehart** [Grammernatzi/XIVComboPlugin#132]
Due to the hotfix, just like the original Combo Plugin, expandedest CTDs when loading.  It needs whatever coding changes the original made to make it stable again.

**Comment by Grammernatzi** [comment]
I have not encountered this at all, and I am playing it with the hotfix, as are a lot of other people playing with the plugin. Are you sure it isn't something on your end?

**Comment by Lockehart** [comment]
It must have been a one off.  Just reinstalled and it's working fine now.  Curious if it was conflicting with something else that needed updating after the hotfix.  CTDs stopped when i removed expandedest initially.  Well it's all fine now apparently, so sorry for wasting your time.  x.x

**Comment by Grammernatzi** [comment]
It's all right, I believe that the crash on startup from XIVCombo was something he just added very recently. From what I recall, it was not having any issues until he changed it, and then he had to fix it after.
