### ISSUE TITLE
phlegma

### ISSUE THREAD

**Issue by doomsz** [Grammernatzi/XIVComboPlugin#133]
they cd is now 40s not 45s anymore... 
![image](https://user-images.githubusercontent.com/80488960/212500710-398e2bfd-fed5-47a3-baeb-d681d61a89c5.png)
![image](https://user-images.githubusercontent.com/80488960/212500740-161229c4-6f0e-4200-a6d3-7cdfbe43e8bc.png)
![image](https://user-images.githubusercontent.com/80488960/212500744-4fdb479d-cc16-4153-8eac-09b708ecd2cc.png)

**Comment by Grammernatzi** [comment]
I will fix this within the hour, thank you for the heads-up; it completely slipped my mind
