### ISSUE TITLE
[PLD] Shield Lob to Holy Spirit via Requiescat?

### ISSUE THREAD

**Issue by eldornoftw** [Grammernatzi/XIVComboPlugin#136]
Heya, I'm finally getting around to leveling PLD, and was wondering if it'd be possible to have the 'Shield Lob to Holy Spirit' setting work with the Requiescat buff in addition to the Divine Might buff? (Note that I'm only late-60s atm, so I'm not sure if this will still make sense once I unlock Confiteor etc at higher levels.. it seems logical at my current level though?)

Thanks in advance ^^
 -eldo

**Comment by Grammernatzi** [comment]
I suppose it could be done, it's worth noting that you want to use Holy
Spirit over Shield Lob whenever possible. I might just change the feature
so that Holy Spirit instead becomes Shield Lob if you're moving and don't
have a way to instant cast it.

**Comment by eldornoftw** [comment]
> I suppose it could be done, it's worth noting that you want to use Holy Spirit over Shield Lob whenever possible. I might just change the feature so that Holy Spirit instead becomes Shield Lob if you're moving and don't have a way to instant cast it.

Ooh yeah, that sounds like a great alternative ^^

**Comment by Grammernatzi** [comment]
Added.

**Comment by eldornoftw** [comment]
Awesome, thank you!
