### ISSUE TITLE
REQUEST : addle/feint lockout feature

### ISSUE THREAD

**Issue by doomsz** [Grammernatzi/XIVComboPlugin#137]
can you add those like the reprisal lockout feature? thanks

**Comment by Grammernatzi** [comment]
Yeah, I was going to add this along with drk/gnb/ranged lockouts for their
aoe mitigation. I'm taking a break from the game for a bit though, so it
will probably be added when I get back, which will likely be in the next
few weeks order to prevent my house from being demolished

**Comment by doomsz** [comment]
i dont think tanks aoe mits need lockout feature tho.. since they can stacks

**Comment by Grammernatzi** [comment]
Not if there's two of the same tank.

**Comment by doomsz** [comment]
ah true... didnt think of that lol

**Comment by Grammernatzi** [comment]
Added.
