### ISSUE TITLE
Request: Option for Storms Eye to Onslaught when out of melee range.

### ISSUE THREAD

**Issue by Foxyfoxe** [Grammernatzi/XIVComboPlugin#140]
Due to the way my hotbars are setup and to keep muscle memory happy I was wondering if it would be possible to add an additional option like the title says since Storms Path already takes care of Tomahawk for me.

I know its important to keep Tomahawk on hotbar for DPS, this would just allow me to hit my gap closer easier when needed. 

Thanks!

**Comment by Grammernatzi** [comment]
That could work. Only issue is that you'd be stuck unable to weave it if you just hit Maim (unless you were out of range), but otherwise, it sounds alright. I'll look at it when I get the time.

**Comment by Grammernatzi** [comment]
Added.
