### ISSUE TITLE
Failed to load (sometimes)

### ISSUE THREAD

**Issue by Xiniox** [Grammernatzi/XIVComboPlugin#144]
I'm having inconsistencies with loading the plugin when I first start up the game. Most of the time it works but sometimes it just fails? Rebooting the game usually fixes it.

**Comment by Grammernatzi** [comment]
Dalamud is in staging right now, so give it some time. It very well may be an issue with the main framework.

**Comment by Xiniox** [comment]
Alright, thanks! ^^
