### ISSUE TITLE
[RPR] Gibbet and Gallows swap feature on Enhanched Gibbet and Gallows Feature

### ISSUE THREAD

**Issue by ar3ea** [Grammernatzi/XIVComboPlugin#145]
Hi, i don't know if this the correct place for asking about it. I really love Enhanched Gibbet and Gallows Feature on RPR but i do prefer start with Gallows (Rear) first instead Gibbet (Flank) especially while you're doing an Opener, i know we already have that feature on Basic Combo (Slice) but i do want to keep it seperate from Basic Combo because i need to looking at the skills to know which one will be enhanced next, that's why i prefer it getting seperated instead combining it into Basic Combo. Thank you!

**Comment by Grammernatzi** [comment]
I'll look into this when I start playing the game again. I've just barely been touching it lately while waiting for Dawntrail.

**Comment by Grammernatzi** [comment]
Added with the upcoming dawntrail update, simply place Gallows on your bar instead of Gibbet and it will turn into Gibbet when Gibbet is enhanced.
