### ISSUE TITLE
Request: GNB Replace Burst Strike with Lion Heart combo

### ISSUE THREAD

**Issue by WorstPirateYouEverSeen** [Grammernatzi/XIVComboPlugin#152]
I would like to request an option that will change Burst Strike into Reign of Beasts (aka Lion Heart combo). I'm not a fan of Bloodfest turning into Reign of Beasts since that button is quite far away in my setup (cuz you only press it once every 2 minutes) and I don't really have any good open spots to put the combo as its own separate button. And since we're no longer spamming Burst Strike during 2 min burst I think turning it into the new combo action would be a nice option.

Thank you for all your work, this amazing QoL plugin and insanely fast updates (I think this was literally the first plugin to be updated for DT)

**Comment by Grammernatzi** [comment]
Seems reasonable to me, I will take a look at it later

**Comment by Grammernatzi** [comment]
I just wanted to mention, this is already technically in the plugin, the Burst Strike/Fated Circle to Bloodfest Feature will also automatically turn Burst Strike into the Lionheart Combo while active. I haven't been able to test that, though. Does that work enough for this, if it does work?

**Comment by WorstPirateYouEverSeen** [comment]
Yes it does work if you have Action Change enabled in the game, if it's disabled it doesn't work. I would still like this as a separate option if possible. I'm just not a fan of oGCDs comboing into GCDs as it can cause issues due to lag and make me use wrong actions, especially with extended action queue time from ReAction. Accidentally using Lion Heart combo will cancel out Gnashing Fang combo.

**Comment by Grammernatzi** [comment]
Fair enough, I do see that the current opener uses the Lionheart combo late, so I understand that. I'll separate the feature from the Bloodfest feature.

**Comment by Grammernatzi** [comment]
There, pushed, it's building now, will be available shortly.
