### ISSUE TITLE
#169 not working

### ISSUE THREAD

**Issue by kenshin330** [Grammernatzi/XIVComboPlugin#153]
# 169 Imperator Confiteor doesn't appear to work at all.

**Comment by Grammernatzi** [comment]
I just found a bunch of bugs in the Requiescat/Imperator features involving
not checking properly for Imperator. It should work with the version I'm
uploading right now, let me know if it doesn't.

**Comment by kenshin330** [comment]
You fixed it all, you're awesome.  Thank you.
