### ISSUE TITLE
Suggestion (GNB)

### ISSUE THREAD

**Issue by Alkeyd** [Grammernatzi/XIVComboPlugin#154]
Would it be possible to make an option similar to PLD? Put the Lion Heart combo to replace the AOE combo like Confiteor replaces PLD's AOE combo?

**Comment by Grammernatzi** [comment]
Yes, I will work on this tomorrow.

**Comment by Grammernatzi** [comment]
Fair, I'll work on fixing that Wednesday night, too.

**Comment by Grammernatzi** [comment]
Both done. Pushing to build.

**Comment by Alkeyd** [comment]
Thank you <3
