### ISSUE TITLE
RDM Request

### ISSUE THREAD

**Issue by mfaisca** [Grammernatzi/XIVComboPlugin#155]
Hi

Could I ask for an option where Jolt changes to Verfire/Verstone if we have the procs?
I know that if we have both of them at the same time that one of them would effectively be hidden, but its a personal pet peeve of mine that I really dislike having the same spell multiple times on my bars (2 buttons showing Jolt when there's no procs).

A bit of a selfish request, but I figured I'd try asking regardless, thank you for all the options you've added and the quick support for DT!

**Comment by Grammernatzi** [comment]
Main issue with this is that it doesn't let you choose between the two. I have an idea, though; perhaps a feature where verstone doesn't change into jolt but everything else applies? Or vice versa.

**Comment by mfaisca** [comment]
That'd work yeah, thank you!

**Comment by Grammernatzi** [comment]
Done, pushing to build.
