### ISSUE TITLE
Swiftcast > Resurrect Suggestion

### ISSUE THREAD

**Issue by xKiisa** [Grammernatzi/XIVComboPlugin#156]
Would it be possible to add a toggle to change "Raise to Swiftcast" to be "Swiftcast to Raise" instead? During certain floors in deep dungeons, abillities may be disabled, which makes it impossible to cast ressurect since Swiftcast has to be casted beforehand. with "Swiftcast to Raise", one could still have the normal ressurection on the hotbar during deep dungeon runs to use :)

**Comment by Grammernatzi** [comment]
I would rather keep it the way it is so you can watch the cool down, but
what I can do is put up a check for the debuff that prevents abilities.

**Comment by xKiisa** [comment]
That sounds like an even better solution, thanks in advance ❤️

**Comment by Grammernatzi** [comment]
Done, building.
