### ISSUE TITLE
Feature Request: Inverse Coil/Den actions between Left/Right combos

### ISSUE THREAD

**Issue by Lunatory** [Grammernatzi/XIVComboPlugin#157]
I would like to have the Rear Dreadwinder action (Swiftskin's Coil) go over the Steel Fangs combo and the Flank Dreadwinder action (Hunter's Coil) go over the Dread Fangs combo. Could you please add an option to switch the two for #295 Coiling Dens (without affecting #296 Coiling Dens Reawakening Option)?

**Comment by Grammernatzi** [comment]
I'm not sure I get why but I can add this, yes

**Comment by Lunatory** [comment]
so I play on controller and my combo setup is generally laid out as following
    4
3      2
    1
Currently, having Steel Fangs on the bottom(1) and Dread Fangs on the right(2) follows this reawakening pattern, but with the way Dreadwinder actions are assigned currently I end up with the flank positional over the bottom button(1), and the rear positional over the side button(3). I could swap the buttons, but that would result in the inverse of the job gauge indicator, and would make the reawakening button order clunky.
I understand if you deem this scenario too uncommon/niche to bother adding it, just figured I'd elaborate on the reasoning for my request.

**Comment by Grammernatzi** [comment]
Fair enough, can you also elaborate what you mean by switching the two for Coiling Dens? Do you mean reading if you're using AoE moves like the single target/AoE swap features for a lot of other jobs?

**Comment by Grammernatzi** [comment]
Or, oops, I misread that wrong; I thought it meant the den features, I'm sleepy; yes, I get what you want now, I'll add the swap as an option.

**Comment by Grammernatzi** [comment]
Added, building.
