### ISSUE TITLE
Feature Request: Replace Twinblood/Twinfang with Serpent's Tail

### ISSUE THREAD

**Issue by Lunatory** [Grammernatzi/XIVComboPlugin#158]
Could you add an option to make Serpent's Tail actions go over Twinblood/Twinfang? I believe they are never available at the same time and it would save having to bind Serpent's Tail without putting the oGCDs over GCDs as in #297 Bloody Fangs and #294 Fanged Tails.

**Comment by Grammernatzi** [comment]
Sure, makes enough sense

**Comment by Grammernatzi** [comment]
Done, building.
