### ISSUE TITLE
Feature Request: RDM Grand Impact options

### ISSUE THREAD

**Issue by 0kie** [Grammernatzi/XIVComboPlugin#160]
Option to **NOT** replace verproc, verthunder II and veraero II into grand impact when you have grand impact ready and have Verproc into jolt and/or RDM AOE combo options enabled

Grand Impact ready lasts longer than Acceleration, and sometimes you may want to save grand impact for later and not use immediately, if you have procs ready you can delay grand impact's use

edit to add that is currently not possible to do the standard opener with verproc into jolt plus, because when you have grand impact ready it is replacing verthunder/veraero 3

**Comment by Grammernatzi** [comment]
For single Target I could easily do this but I am curious why you would want it gone for aoe? If you're using acceleration, why would you want to use veraero/thunder 2? To stack it with dual cast I guess?

**Comment by 0kie** [comment]
Appreciate the fast response.

About the aoe option, I just realized it doesn't make sense because grand impact replaces impact anyway, so it is impossible to do accel > impact and save grand impact for later, that was my bad x_x

**Comment by Grammernatzi** [comment]
The reason I asked is because always having the option to use Grand Impact
without having to manually drag Jolt or Impact to your bar would be nice.
So if all it did was replace jolt normally on your single target, you could
still access it at any time if it was always replacing your AOE. That's how
I was planning to have it set up.

**Comment by 0kie** [comment]
Yes, it makes sense to always replace in the aoe, that was my bad forgetting it replaces impact already on vanilla.
Just in single target that it becomes a problem not having access to verproc/verthunder III/veraero III because of the opener and ogcd alignment (possibility of saving grand impact for later use)

**Comment by Grammernatzi** [comment]
Yeah, so that's what I'm doing atm. It'll always replace AoE but it will
only replace what would otherwise be Jolt in Verproc into Jolt. That should
give you the functionality you want.

**Comment by Grammernatzi** [comment]
Done, pushing
