### ISSUE TITLE
MCH Hypercharge Feature displays incorrect icon

### ISSUE THREAD

**Issue by athuy** [Grammernatzi/XIVComboPlugin#161]
Auto Crossbow is replaced with Heat Blast when not in Hypercharge.
Heat Blast is selected even when Blazing Shot is unlocked (but not available due to being out of Hypercharge).

This doesn't actually affect the usage of the skill, as Hypercharge will appear when the battery gauge is at or above 50.
![image](https://github.com/Grammernatzi/XIVComboPlugin/assets/91638195/8ea90bb6-ce97-4a00-a93a-b13b00c78d23)

![image](https://github.com/Grammernatzi/XIVComboPlugin/assets/91638195/1e21ee40-b669-4932-a738-1664add8a3fe)

![image](https://github.com/Grammernatzi/XIVComboPlugin/assets/91638195/fc0c29d9-f1f0-4b45-98a5-0bd0036b2419)

**Comment by Grammernatzi** [comment]
I believe this should be fixed now, it was a bit of an oops on my end trying to make it sync for lower levels. I might finetune it later but to be fair Autocrossbow does not really NEED to sync into Heat Blast anyway.
