### ISSUE TITLE
Heat Blast into Hyper charge isnt accounting for the Blazing Shot upgrade

### ISSUE THREAD

**Issue by Jhazor** [Grammernatzi/XIVComboPlugin#162]
as per title Blazing shot isnt being overridden by Hypercharge when not over heated on MCH

**Comment by Grammernatzi** [comment]
It's worth noting that if you drag Heat Blast onto your bar it will auto upgrade but work with the feature just fine. However, I will fix this anyway, because I did forget.

**Comment by Grammernatzi** [comment]
Done
