### ISSUE TITLE
Feature Request: RPR Enshrouded gibbet/gallows

### ISSUE THREAD

**Issue by Ashiidia** [Grammernatzi/XIVComboPlugin#164]
Hi, I'd like to see an option to replace gibbet/gallows with enhanced version (alternating them every gcd), but only during enshroud because I want normal gibbet and gallows positional to remain unchanged for easier positional tracking

This option is already added in MKhayle's fork but would be nice to not install another combo for one extra tweak

Thank you!

**Comment by Grammernatzi** [comment]
Sure, I can add this option.

**Comment by Ashiidia** [comment]
Don't think you pushed it :(

**Comment by Grammernatzi** [comment]
I did, try reinstalling.

**Comment by Ashiidia** [comment]
Maybe i'm looking at the wrong repo, but this repo didn't change for 2 days (last update was vpr/mch changes ) and last reaper change was 2 weeks ago. There was no version change or update both with and without reinstalling.

**Comment by Grammernatzi** [comment]
Oh, you're right, maybe there was an error with pushing. I will double
check once I'm on the computer.
