### ISSUE TITLE
Suggestion [PCT]

### ISSUE THREAD

**Issue by Appl3Tree** [Grammernatzi/XIVComboPlugin#166]
Similar to other classes where main combo is replaced to avoid wasting gauge, Picto's main combo being replaced by Subtractive Palette/Holy in White if white paint is about to cap or if the Palette Gauge is about to pass 100.

**Comment by Grammernatzi** [comment]
This is already planned for regular XIVComboExpanded as a 'secret', so sure. I can look into it.

**Comment by Grammernatzi** [comment]
Added
