### ISSUE TITLE
MCH

### ISSUE THREAD

**Issue by TenshiOskar** [Grammernatzi/XIVComboPlugin#167]
Blazing Shot to Hypercharge still broken, but i see your fix and im up to date so i dunno.  Thanks for the mod!

**Comment by Grammernatzi** [comment]
Actually fixed it this time, missed a thing in the code. Once again going to remind people again, though, that if this happens in the future, just drag the unupgraded action onto your bar (Heat Blast) and let it auto upgrade and it will work fine.
