### ISSUE TITLE
RPR gibbets and gallows all on slice

### ISSUE THREAD

**Issue by Nypheena** [Grammernatzi/XIVComboPlugin#168]
would it be at all possible for there to be a version of "gibbets and gallows feature" that puts it all on slice like it originally did back in endwalker release without needing to use the enhanced gallows and gibbets feature since I have them on E and R and use that to let me know which positional is next so when both swap for whats next I can't tell, a child feature would be great

on a side note, what is "gibbets and gallows feature swap" exactly?

**Comment by Grammernatzi** [comment]
I didn't change anything? It should still all be on slice, and the combo communio feature already accounts for Perfectio.

**Comment by Grammernatzi** [comment]
Or, oh, I see, the Enhanced Gibbets and Gallows Feature for some reason is required for that, lemme mess with it.

**Comment by Grammernatzi** [comment]
Okay, I added that option, I don't get what you mean about the combo communio thing though, is it not working? I don't exactly have level 100 Reaper, it's just checking for if Communio is different and if it is, it puts Perfectio onto stuff.

**Comment by Grammernatzi** [comment]
No prob, and thanks for letting me know!
