### ISSUE TITLE
Monk dont work

### ISSUE THREAD

**Issue by Abraham91** [Grammernatzi/XIVComboPlugin#169]
Hi! Monk's features doesn't work , i supose that its because those changes with gauge and buff's system.
I dont know about how hard its to code it but if you can do the following suggest i will be very happy with it.

Dragon Kick --> Bootshine (when have stacks of Opo-opo fury)
Twin Snakes --> True Strike (when have stacks of Raptor fury)
Demolish --> Snap Punch (when have stacks of Coeurl fury)

Thx for your work! ^^

**Comment by Grammernatzi** [comment]
Monk does work, specifically with those features (which are already in the plugin). Reinstall it if you need to. I just tested it out and if you're not seeing these features, that means something is wrong on your end (you can even see the commit [here](https://github.com/Grammernatzi/XIVComboPlugin/commit/749576219fbc2c67a115654282086d0617b5b1a4).

**Comment by Zeemgeem** [comment]
I'm also having issues with monk, but only their 1-2-3 in Perfect Balance. It consistently gets two of the same sticker instead of one of each. I've tried reinstalling multiple times.

https://youtu.be/iHwFjJ5wF-A?si=92qw6gbBOmMj6lJx

**Comment by Appl3Tree** [comment]
Having issues with any of the combos changing except AOE combo. Worked great w/ the DT updated up until the 1.5.0.23 change.

**Comment by Grammernatzi** [comment]
The combos are working fine for me, so I'm confused. Zeem being able to get most of it to work but almost nothing working for appl3tree is very odd. It is worth noting that this plugin is built for and uses the staging version of dalamud. I will check out the 1-2-3 aoe combo problem though.

**Comment by Grammernatzi** [comment]
I just fixed the AoE combo, it was because the gauge was broken before and the values were wrong. Again, I would recommend everyone having issues to try it on staging. The gauges in release version may be borked.

**Comment by Abraham91** [comment]
That works for me , i swap to Stg and everything is working well. Thanks

**Comment by Appl3Tree** [comment]
I can confirm as well, swapped to stg and now everything's working great!

**Comment by Grammernatzi** [comment]
It shouldn't be needed for long, it just seems they haven't pushed the Monk gauge changes to release yet. I will keep this issue up until they do. I aim to keep these compatible with release, but I jumped the gun and thought it was ready when MKhayle released their MNK stuff too. I imagine that also has the same issue atm
