### ISSUE TITLE
Reaper  - Gibbets and Gallows and Gibbet gallows swap feature not working on Executioner Gibbet and gallow

### ISSUE THREAD

**Issue by Szaltax** [Grammernatzi/XIVComboPlugin#170]
First i would like to say a huge thank you for all your work.  This has helped significantly helped playing on controller.

I found an issue with one of the features.  The Gibbet and Gallows feature and Gibbet/Gallows Swap are not working correctly when procc'd for executioner stacks.
Slice switches correctly but Shadow of death does not.

Everything is good on the normal versions just not the executioners (After using Gluttony).

Here is a screen shot, Left side is regular gibbet gallows buttons, Right is Slice working but Shadow of Death not working
![executioner gibbet and gallows](https://github.com/user-attachments/assets/844278a2-fd1a-460f-af65-1fd2879dbe31)

**Comment by Grammernatzi** [comment]
I found a missing executioner check for that feature and added one, can you see if it works now?

**Comment by Szaltax** [comment]
Sorry for the delayed response, yes that fixed it.  Thank you so very much

**Comment by Grammernatzi** [comment]
No prob, good to know!
