### ISSUE TITLE
DRG

### ISSUE THREAD

**Issue by doomsz** [Grammernatzi/XIVComboPlugin#171]
![image](https://github.com/user-attachments/assets/1ba8c2bb-1de5-4696-84ab-8eaf5b6cf801)
the DRG is changed now.. we get 3 charges of nastrond instead of its cooldown..
so if i didnt use stardiver at all it will lock the hotbar into nastrond (since its on cd but no charge left) and i thus cant use stardiver (if i didnt use it before nastrond 3 stacks used)

**Comment by Grammernatzi** [comment]
Got it, changing it to track the buff instead, will push that soon.

**Comment by Grammernatzi** [comment]
Oh, but I guess it needs to work differently now. This feature probably should just replace Nastrond with Stardiver whenever it's available, then?

**Comment by doomsz** [comment]
nah imo nastrond should be priority over stardiver since stardiver locks your chara.. and sometimes ppl need to "time" when to use it.. meanwhile nastrond you can just use whenever

**Comment by Grammernatzi** [comment]
Then honestly I might just delete it and say just go for Stardiver over Dragonfire Dive? Because Nastrond and Stardriver aren't things you can easily put on top of each other anymore.

**Comment by doomsz** [comment]
ah ic... maybe can just keep the other option, incase ppl will need it.. but yeah looks like im switching to dragonfire dive now

**Comment by Grammernatzi** [comment]
Also both ways of doing Stardiver to Nastrond are incompatible with the current opener:
![image](https://github.com/user-attachments/assets/3bd4c58d-44c1-4cc5-9674-7b2e97db2018)

Meanwhile, Stardiver to Dragonfire Dive DOES work with it since the DPS doesn't change if you switch them in the opener (it's mostly just a preference thing).

**Comment by doomsz** [comment]
the stardiver to dragondive conflict with yosshi-p feature
![image](https://github.com/user-attachments/assets/a547ff44-64b2-4f05-993c-b096a67915a3)
rise of dragon wont show if you are not in EYE mode :(

**Comment by Grammernatzi** [comment]
You shouldn't be using rise of the dragon outside of eye. But I'll take a look at the code later.

**Comment by Grammernatzi** [comment]
Fixed it, pushing.
