### ISSUE TITLE
[BLM] Firestarter prio over paradox in AF3

### ISSUE THREAD

**Issue by Ashiidia** [Grammernatzi/XIVComboPlugin#172]
Hi, currently when you're in astral fire 3 and have both paradox and firestarter, paradox takes priority. This happens when you use new manafont that gives paradox back when you still have firestarter proc. Would be nice to have an option for fire 3 proc having priority over paradox to avoid overwriting and losing firestarter proc by casting paradox. Currently there's only an option for it when you're in astral fire 1.

**Comment by Grammernatzi** [comment]
I'll look at this tonight, I probably accidentally shifted the paradox priority so it overwrites firestarter somehow.

**Comment by Grammernatzi** [comment]
Alright, this has been fixed, pushing.
