### ISSUE TITLE
[Suggestion] Brotherhood into Riddle of Fire

### ISSUE THREAD

**Issue by lasGustavo** [Grammernatzi/XIVComboPlugin#176]
Essentially swapping the current available feature into BH taking priority as the button when both are up, this is to properly execute the MNK openers and burst windows.

**Comment by Grammernatzi** [comment]
I have noticed it switched, I just completely forgot because I don't use
this feature. So I will update it for better priority, maybe tomorrow.

**Comment by Grammernatzi** [comment]
Applied, just modified the priority of the original feature so that people don't have to mess with hotbars. If you're using this feature I'd recommend using DelvCD or JobBars or something to track the cooldowns of each because either way I did it, important cooldowns would be hidden.
