### ISSUE TITLE
SMN

### ISSUE THREAD

**Issue by doomsz** [Grammernatzi/XIVComboPlugin#177]
necrotize didnt change to ED, but fester did
![image](https://github.com/user-attachments/assets/665778fe-0617-49f3-b4e8-967fd2ef70d7)

**Comment by Grammernatzi** [comment]
Likely forgot to add it to the list of actionIDs, but the auto upgrade of
Fester should make it work fine. I'll fix it along with some other stuff
I'll be adding, I've been busy finally bothering to finish MSQ this week

**Comment by doomsz** [comment]
what !??! you still havent done MSQ lol

**Comment by Grammernatzi** [comment]
Should be fixed now
