### ISSUE TITLE
Some icons aren't changing.

### ISSUE THREAD

**Issue by HananaBananana** [Grammernatzi/XIVComboPlugin#179]
These are all visually. The buttons still work but you have to guess which ability it's going to use/if you have procs.

RPR: Slice and Spinning Slice aren't changing VISUALLY to Gibbets/Gallows/Guillotine.
DNC: Fan Dance 1 isn't changing to Fan Dance III procs. 

These are the only two classes I've noticed.

![image](https://github.com/user-attachments/assets/9111ab99-2fa0-475c-965d-36376e766b5d)

The icon shows and reads Infernal Slice but the tooltip shows Gibbet and when I use it, it uses Gibbet.

EDIT: At least for RPR, if you turn off infernal slice combo and night scythe combo, it replaces it icons appropriately

**Comment by Grammernatzi** [comment]
As others have mentioned, this is likely a plugin conflict issue. Try running the plugin by itself after reinstalling and see if it does it (you can just rename your installedPlugins folder temporarily to do this)

**Comment by Grammernatzi** [comment]
Closing due to no response
