### ISSUE TITLE
Request: Make #307 apply to Den actions too

### ISSUE THREAD

**Issue by Lunatory** [Grammernatzi/XIVComboPlugin#180]
Hello, I wanted to request to have # 307 Coiling Dens Swap Option affect the Pit of Dread actions Hunter's Den and Swiftskin's Den too, making Swiftskin's Den go over Steel Maw and Hunter's Den go over Dread Maw instead.

**Comment by Grammernatzi** [comment]
I'll just make that a separate option (so people don't feel forced to use flip one just to flip the other). I'll work on it tomorrow.

**Comment by Grammernatzi** [comment]
Added and pushing.
