### ISSUE TITLE
Feature Enhancement/Bug Report: Forked Raiju not going over Armor Crush if combo option is disabled.

### ISSUE THREAD

**Issue by Lunatory** [Grammernatzi/XIVComboPlugin#182]
Currently **# 163 Armor Crush / Forked Raiju Feature** only works if **# 149 Armor Crush Combo** is enabled. Since I need to have both AE and AC on my hotbar, I don't have combo on for both, but would still like to be able to use # 163.

**Comment by Grammernatzi** [comment]
I likely forgot this because of the Huraijin change. I'll work on making it, well, work.

**Comment by Grammernatzi** [comment]
Fixed and pushing.
