### ISSUE TITLE
[DRG] request

### ISSUE THREAD

**Issue by doomsz** [Grammernatzi/XIVComboPlugin#183]
can you add 
![image](https://github.com/user-attachments/assets/70c1af95-9864-41d4-bb8c-275511c8fb18)
to behave like raiden thrust ?
![image](https://github.com/user-attachments/assets/4fd07828-f248-4756-af8a-ddef064d4b20)
![image](https://github.com/user-attachments/assets/a76317e5-8e1c-4ab0-b1d3-36baf49214f5)

**Comment by Grammernatzi** [comment]
To apply to both combos, is what I assume you mean? I suppose I can add that as an option.

**Comment by doomsz** [comment]
yep2

**Comment by Grammernatzi** [comment]
I can add that by default I suppose since I don't even use the two combos feature (I used the 'press disembowel to change combo' thing instead) so it wouldn't really affect me. Though if someone complains that it's less pretty I suppose I could add an option later.
