### ISSUE TITLE
[BRD] Evil Radiant Voice Feature

### ISSUE THREAD

**Issue by Ashiidia** [Grammernatzi/XIVComboPlugin#185]
hi, some of the bard openers are using radiant finale first instead of battle voice so would be nice to have inverted feature that switches finale into battle voice instead

**Comment by Grammernatzi** [comment]
I can look into adding this, it may just be a bit annoying to do so since the feature is already a bit spaghetti.

**Comment by Grammernatzi** [comment]
Rewrote the Radiant Finale-based stuff and added this into it.
