### ISSUE TITLE
(Silly) Feature Request: SMN Physick > Lux Solaris

### ISSUE THREAD

**Issue by Lunatory** [Grammernatzi/XIVComboPlugin#186]
This is a silly one since most people won't even have Physick bound to their hotbar so I understand if you don't want to clutter the plugin, but Physick into Lux Solaris when it is available would be a fitting replacement.

**Comment by Grammernatzi** [comment]
Mostly I'm just too lazy to add something I don't think anyone will really actually make use of (since almost no SMN uses Physick). So I mean, it doesn't exactly make zero sense, but, y'know
