### ISSUE TITLE
Feature Request: DNC - Standard Step and Technical Step onto one button

### ISSUE THREAD

**Issue by VVDMS** [Grammernatzi/XIVComboPlugin#187]
Hello! I would like to ask if it would be possible to add a feature to DNC that merges Standard Step and Technical Step into one button. This way, we could use Standard Step & Dance, and then it would automatically switch to Technical Step. Once Standard Step is off cooldown, it would switch back to Standard Step and continue in this manner

**Comment by Grammernatzi** [comment]
I can see how it might cause problems if you're playing without countdowns in casual content (because then you want to start with tech step, not standard step) but I assume you'd just have technical step ready by itself to use if this happens? And this would mostly just be for convenience otherwise.

**Comment by VVDMS** [comment]
I'm a bit confused. Don't you always want to start with Standard Step during pre-pull? I think another plugin used to have this feature, but I don't think it works anymore. I solved the cooldown tracking by having both dances on the screen.
![Screenshot_27](https://github.com/user-attachments/assets/3968eb8c-be72-4292-bd4f-879dd3066c5b)

The way it worked was that after using Standard Step and the dances, it would change to Technical Step and the dances. Once Standard Step was off cooldown, it would switch back to Standard Step, and so on. I hope this makes sense.

**Comment by Grammernatzi** [comment]
Yes you do but you often cannot in casual content because of instant pulling. It's actually better to technical step if you don't have a countdown so that you can use the standard step during technical step, because missing a standard step in your technical finish is a DPS loss.

**Comment by VVDMS** [comment]
I get that. I was just curious if there was any chance of getting this optional feature added. It would be great if so, but I understand if not. I just think it would be fine if it were its own feature, not connected to anything else, so anyone could just tick it on / off as needed

**Comment by Grammernatzi** [comment]
Apparently this changes at level 100 due to new moves. It would still be an issue in synced content, though.

**Comment by Grammernatzi** [comment]
I mean yes, you can have it as an optional feature. I am just saying that you still would want the ability to press technical finish separately just in case.

**Comment by VVDMS** [comment]
That's fine with me. I think the other plugin worked the same way, since it changed Standard Step to Technical Step, not the other way around, so I was still able to press Technical Step on its own if needed

**Comment by Grammernatzi** [comment]
I will work on it later then. I have a busy few days but it shouldn't be too complicated.

**Comment by VVDMS** [comment]
Thank you so much for the fast replies and for adding it! As well as for the plugin
