### ISSUE TITLE
Dancer's Reverse Cascade AoE Always Enabled

### ISSUE THREAD

**Issue by Fynzou** [Grammernatzi/XIVComboPlugin#188]
Under Dancer's "Reverse Cascade Combo" there is the option "Change on AoE"

This appears to always be active, even when it is unchecked. I have disabled every other option to make sure another option was not causing it.

**Comment by Grammernatzi** [comment]
Just hotfixed this, thank you for letting me know. I guess nobody ever ran it disabled before, I'm surprised I just heard about it now
