### ISSUE TITLE
Fisher changes?

### ISSUE THREAD

**Issue by ALymphocyte** [Grammernatzi/XIVComboPlugin#191]
I don't actually combine Cast and Hook because I've noticed that it makes me accidentally Hook when I'm trying to Cast because I haven't realized I already have. I do, however, make these changes:

1. combining Chum and Cast

```cs
            if (actionID == All.Chum && LocalPlayer is not null)
            {
                if (LocalPlayer.CurrentGp < 100)
                    return All.Cast;
                if (LocalPlayer.CurrentGp < 150 && HasEffect(All.Debuffs.InefficientHooking))
                    return All.Cast;
                if (HasEffect(All.Buffs.Chum))
                    return All.Cast;
            }
```

2. combining Hooksets with Hook

```cs
            if (actionID == All.PrecisionHookset || actionID == All.PowerfulHookset)
            {
                if (CanUseAction(All.Hook) && !HasEffect(All.Debuffs.InefficientHooking))
                    return All.Hook;
            }
```

Relevant numbers:

```cs
// All
            Cast = 289,
            Chum = 4104,
            PrecisionHookset = 4179,
            PowerfulHookset = 4103,
            Hook = 296,

// Buffs
                Chum = 763,

// Debuffs
                InefficientHooking = 764,
```

Completely up to you whether you find them interesting, but this saves me two Fisher hotbar spaces and I've been liking it a lot.

**Comment by ALymphocyte** [comment]
Oh, the specific reason I have the `CanUseAction` check for the Hooksets is so you can tell them apart when you're not fishing, which makes it easier to rearrange the hotbar.

**Comment by Grammernatzi** [comment]
I barely touch Fisher but if you have tested these I can easily add them, ye

**Comment by ALymphocyte** [comment]
Yep, I use them myself.

**Comment by Grammernatzi** [comment]
Added, made them compatible with some other stuff and tested to make sure they work with them on or off. For if other people wish to use them with what they already have enabled, of course.
