### ISSUE TITLE
Monk's Meditation Reminder below lv15

### ISSUE THREAD

**Issue by Nysterian** [Grammernatzi/XIVComboPlugin#192]
I just made an alt, and already had "Meditation Reminder" on, but since pugilist only gets that skill at lv15, all it does is replace every single skill in my hotbars to one that I cannot use, effectively making pugilist below lv15 unable to be played.

Of course, it can be easily fixed by turning the option off, but I don't think that's the intended mechanic.

**Comment by Grammernatzi** [comment]
Hotfixed, thank you for letting me know
