### ISSUE TITLE
SGE Phlegma into Psyche

### ISSUE THREAD

**Issue by mfaisca** [Grammernatzi/XIVComboPlugin#195]
Suggestion to transform Phlegma into Psyche if Psyche(new L92 ability) is off cooldown (with priority over Phlegma into Dyskrasia/Toxikon)

or some other variation you think might fit well

**Comment by Grammernatzi** [comment]
Probably only if the GCD is rolling or you're out of Phlegma charges since Psyche is a cooldown, but otherwise sure

**Comment by Grammernatzi** [comment]
Added.
