### ISSUE TITLE
Feature Request: Lucid Dreaming Reminder Customizations

### ISSUE THREAD

**Issue by 0kie** [Grammernatzi/XIVComboPlugin#196]
Was wondering about the possibility of changing how lucid dreaming reminder currently works.
Would be possible to add a textbox like the "Melee distance offset", but for "MP before using lucid dreaming" instead?

Current behaviour has cooldowns becoming lucid dreaming when they are not up and bellow 9000 mp
My request would be they changing into lucid dreaming when it is bellow that set value chosen by the user

Also, would be possible to add a custom "time offset" to prevent cooldowns from becoming lucid dreaming?
For example, we set this offset as X seconds, then when the cooldown is "X" seconds away from being up it don't swap to lucid dreaming.

**Comment by Grammernatzi** [comment]
It would be a fair bit of work but I could probably add that. I can look into it.

**Comment by Grammernatzi** [comment]
Added, thank you for waiting.
