### ISSUE TITLE
DNC Suggestions

### ISSUE THREAD

**Issue by mfaisca** [Grammernatzi/XIVComboPlugin#197]
Prevent Resource waste:
- Cascade/Windmill into Fan Dance I/II if we're at 4 stacks (when GCD is rolling)
- Cascade/Windmill into Saber Dance if we're at 90+ Esprit

Extra option under both skills above:
 - Additionally, if Devilment is active use all stacks (when GCD is rolling)
 - Additionally, if Devilment is active, use if 50+ Esprit.

**Comment by Grammernatzi** [comment]
The first two and the last one are already in XIVComboExpanded, so sure. Probably won't add the third one, though, I apologize, unless they also add that.

**Comment by Grammernatzi** [comment]
Added.
