### ISSUE TITLE
Feature Request: Replace Sprint with Isle Sprint when on Island Sanctuary

### ISSUE THREAD

**Issue by faultlline** [Grammernatzi/XIVComboPlugin#198]
Not sure if this is possible but it would be nice to have the same keybind with all the sprint spam

**Comment by Grammernatzi** [comment]
Doesn't SimpleTweaks do this?

**Comment by faultlline** [comment]
Think it was disabled after DT, didn't find anything there

**Comment by Grammernatzi** [comment]
Strange. I went ahead and added it, though, so there you go.
