### ISSUE TITLE
Feature Request: Replace Cure with Cure II when Freecure is active and Cure II is unlocked

### ISSUE THREAD

**Issue by Nightfury58** [Grammernatzi/XIVComboPlugin#199]
For all those gamers who like using Cure I. Wouldn't hurt to have. Though, I get if this doesn't exist because Cure II has a longer cast time; maybe it would classify as an Option instead of a Feature?

**Comment by Grammernatzi** [comment]
I hate Cure 1 with an undying passion, but anyhow, this is already in as a hidden part of the Cure 2 to Cure 1 level sync feature, because someone requested it before.

**Comment by Nightfury58** [comment]
Ah, I see, so you'd rather people literally just replace Cure 1 with Cure 2 than even dare give them the OPTION of fishing for Freecure, eh? I get it haha

**Comment by Grammernatzi** [comment]
I mean, it works the way you want it to. Just also put Cure 1 on your bar. But yeah, hope that does work for you.
