### ISSUE TITLE
[RPR] Request

### ISSUE THREAD

**Issue by doomsz** [Grammernatzi/XIVComboPlugin#200]
i know you said you hated the current rpr enshroud.. but it has been done might aswell
can you add sacrificium and perfectio into it

**Comment by Grammernatzi** [comment]
I mean, fair, if Expanded already has it. Though I think I did add Perfectio to it already, but I may be wrong. I didn't add Sacrificium though.

**Comment by Grammernatzi** [comment]
About to be added in next update.
