### ISSUE TITLE
Request: [DNC] Expand "Dance Step Feature" to accept multiple Action IDs

### ISSUE THREAD

**Issue by eldornoftw** [Grammernatzi/XIVComboPlugin#201]
Heya, 

I've been getting back into DNC recently and am wondering if it'd be possible to expand the Dance Step Feature to allow multiple Action IDs to be assigned to each dance step, please? In my specific case, I'd like to be able to assign both Fan Dance and Fan Dance II to become Jete (Green) while dancing. I also find that if my AoE abilities are replaced by their procs then they don't change into dance steps. Having the existing fields accept a comma separated list would give the most flexibility, but if that's too much work then even just having an optional second field for each dance step should be enough to solve my current problems 🙏

**Comment by Grammernatzi** [comment]
This would honestly be quite a lot of work and would require rewriting a fair bit of it. And, by AoE abilities, do you mean if you change them via the feature or the vanilla changing?

**Comment by eldornoftw** [comment]
That's discouraging to hear.. I would offer to look into it myself, but I have no any experience with FFXIV plugin development 😞

As for the issue with AoE abilities, it occurs when using the 'AoE to Procs' feature. I have 'Single Target to Procs' and 'AoE to Procs' both enabled, and the Dance Step Feature configured with 15989 (Cascade), 15990 (Fountain), 16007 (Fan Dance), 16005 (Saber Dance). When I start dancing normally, Cascade / Windmill both become Emboite (Red), Fountain / Bladeshower both become Entrechat (Blue), Fan Dance becomes Jete (Green), and Saber Dance becomes Pirouette (Yellow). With the Silken Symmetry / Silken Flow buffs, Reverse Cascade / Fountainfall correctly become Emboite / Entrechat, but Rising Windmill / Bloodshower do not. Hopefully the attached picture will help clarify what I mean.

![image](https://github.com/user-attachments/assets/83dc5dfb-383f-423c-9e53-576b2d426510)

**Comment by Grammernatzi** [comment]
I can definitely fix that, at least; I think that is an error because the combos were written in Shadowbringers before the aoe combos/procs turned into dance steps (which I believe was added in Endwalker, but may be mistaken). That said, like I said with the dance steps thing, that'd require rewriting the IDs into an array/list/whatever and converting people's existing IDs into said list, as well as figuring out how to do it via Dalamud UI. I will say, though, that you could use Fan Dance I to II to get around this issue, but that could be a little janky since it requires you to use your aoe combo (without procs) before Fan Dance I turns into II. Perhaps in the future, I could make it more accurate and register aoe procs as well by checking whatever your last weaponskill used was in general.

**Comment by eldornoftw** [comment]
Ahh, makes sense. Yeah, I did try Fan Dance I to II, but as you say it is rather janky; I don't use the equivalent single target to AoE type options on any of the other jobs so it'd take some getting used to. 

Regarding the rewriting IDs and converting existing settings: totally, though that's why I was wondering about having it as an optional extra field for each dance step instead.. Like, just duplicate the existing 4 fields and handle them in the same places as the original 4, where maybe the only difference is if they have the default value/0 then they're ignored (instead of reverting to the default actions like the original 4 do). I'd hope that wouldn't impact anybody's existing configurations and wouldn't require massive structural changes - though as I said I haven't got any FFXIV plugin development experience so I could be mistaken.

**Comment by Grammernatzi** [comment]
I mean, I could add it as an edge case, just feels a bit weird. But I don't see too much of a problem with it I guess. Probably will be slow with it though since it's a busy week for me and it's mostly a cosmetic thing.

**Comment by eldornoftw** [comment]
Yeah, fair enough! Thanks - and no rush, I can certainly work with the current setup for the time being, but shall look forward to (hopefully) seeing it at some point ^^

**Comment by Grammernatzi** [comment]
Went ahead and just added the singular edge case because meh. Will be added in next update.
