### ISSUE TITLE
BLM Ice Paradox

### ISSUE THREAD

**Issue by thebrimmy** [Grammernatzi/XIVComboPlugin#202]
I am not sure if I am just not doing something right. However, if I have Paradox procced but the Fire 1 to Fire 3 feature enabled, Paradox is not useable within Ice phase. Fire 3 will turn into Paradox only in fire phase, which was the previous expectation when DT launched, but has since been updated to allow an Ice Paradox.

**Comment by Grammernatzi** [comment]
Fixed, thank you for letting me know.
