### ISSUE TITLE
[Feature Req] BLM Despair to Flare Star

### ISSUE THREAD

**Issue by athuy** [Grammernatzi/XIVComboPlugin#204]
This is sort of doable if you have both the Flare to Flare Star and Flare to Despair features enabled, but it's a bit clunky for my admittedly specific circumstance of doing single target Fire 4s into Flare (enemies were too spread apart but got grouped up) and going from Fire 2s into despair (multiple enemies died, not enough mp to start a fire 1/4).

It also makes sense to just change Despair to Flare Star since it's the exact same move down to the recast timers, but with more potency.

**Comment by Grammernatzi** [comment]
What are you suggesting exactly? That Despair always turn into Flare Star when Flare Star is available or that Despair become Flare Star after you are at 0 MP? The latter would make the current opener impossible and the former would easily kill your AF timer because Flare Star doesn't refresh Astral Fire (and no, I'm not gonna make it check for the timer being under a certain amount).

**Comment by Grammernatzi** [comment]
Actually, I just thought up something that might be better; I still think Despair to Flare Star is a bit of a problem from what I mentioned (though I do not mind you arguing in favor of it as I'm not _entirely_ unconvinced), but I'd never considered Blizzard 3/High Blizzard 2 to Flare Star. You never want to use them without spending Flare Star, and if you are really in a pinch where you need to refresh your timer but Despair would take too long to cast, Transpose > Paradox > Blizzard is only a very minor DPS loss over Blizzard 3.

**Comment by athuy** [comment]
I don't see how this would make any openers impossible. You can only use Flare Star when at 6 stacks, and you can only use Despair/Flare when you have >=1000 MP.
I don't really look at openers, so I'm not sure if this is the on you're referring to but if it is, I don't see any issue where you'd want to use flare star instead of despair and vice versa.

You bring up a good point that Despair refreshes enochian but flare star doesn't, though that's also a bit of a niche circumstance. An alternative could be Fire 4 to Flare Star since neither refresh enochian and you'd lose a usage of Flare Star if you overcap coming out of Astral Ice. On the other hand, Flare Star has a longer cast time than fire 4 so you wouldn't be able to do the other niche scenario where you already lost a Flare Star cast and want to greed a Fire 4 to dodge a mechanic.
![image](https://github.com/user-attachments/assets/70ab01e1-c9c0-4eb2-b2af-53b97f395dac)

**Comment by Grammernatzi** [comment]
So, first off, the opener would indeed be impossible if Flare Star only replaced Despair if you were at 0 MP, which was the first pick. And I could have it also replace Despair if Flare Star was available and you were >= 1600 MP though, since that only happens during the opener anyway and would fix that scenario.

The other option, Flare Star replacing Despair if it's available, isn't feasible because I just labbed it, and if you use two instant casts (Thunder or Xenoglossy) during Astral Fire and use Flare Star before Despair, your timer *will* run out. You could use your Firestarter'd Fire 3 early to mitigate this, but that would be a DPS loss over saving it for the transpose weave from Umbral Ice. So I don't think that's a good option. The first one may be, though.

**Comment by athuy** [comment]
I've been doing ice opener, so I wasn't aware that you just skip over that in DT. MP is a little wonky looking with this since I'm used to the 3 umbral hearts for fire phase.

Labbing the opener out + rotation out, Flare Star always replacing Despair if available doesn't break anything in the opener. There's a lot of niche scenarios I can think of that make Despair -> Flare Star problematic during you AF phase:
* Despair -> Flare Star if MP >= 1600 means you must Despair before Flare Star normally, or you'll Flare Star -> Despair if you somehow entered AF in a wonky way (2 hearts instead of 3, missing MP, etc.)
* Despair -> Flare Star if MP >= 1600 OR MP < 1000 means you must Despair before Flare Star.
* Despair -> Flare Star always means you force people to use their firestarter before Flare Star OR an swift/triplecast on Despair if they're playing slow BLM/play badly

I'm personally fine with the 2nd and 3rd options, but I don't like the 3rd one since it forces a certain playstyle.
An alternative is Fire 4 -> Flare Star. This doesn't break anything other than maybe the niche scenario where you want to slidecast 0.2s sooner in the opener or if you don't care about overcapping.

I put way too much thought into this. Maybe I should just put Flare Star on my XHB.

**Comment by Grammernatzi** [comment]
Ice first has been a damage loss for the opener for a _looong_ time. But yeah, the second option seems the best, so I'll go for that.

**Comment by bennolor** [comment]
I stumbled into this and did some experimenting. (Not gonna do a pull request as I have 0 Experience with both Dalamud and C#)

According to my playing around the following solution seems most desirable to me and achievable(I'm unsure however where nd how the call towards the LocalPlayer Interface for the mana should happen):

```cs
AstralSoulStacks >= 6 && ( lastComboMove == BLM.Despair || MP == 0 || MP >= 2400) ? Flarestar : Despair
```
 Outside of the Opener you generally always want to cast Despair first which this accounts for with the `lastComboMove` or the MP=0 if you decide to use i.e Xenoglossy or Thunder first. 
 
 As there is no realistic (yes you can chug MP potions but that denies buff potions and is in general a dead strat) situation where  Astral Soul can reach 6 Stacks without having come from 3 Umbral Hearts and 10k Mana and being at 1200 mana, outside of a short fire phase (i.e from Fire Opener) followed by Manafont, This accounts for almost all situations. 
 
 The 2400 cut off for the Manafont line is chosen as its the cutoff for F4 + Despair. Generally that situation should have you at 2800 Mana but 2400 is the important cutoff after which your next cast SHOULD be Despair.
 
 
 The one drawback is that this doesn't account for forcing an early Flarestar under Buffs but thats a rare 90 potency loss and would be side-step able through either manually casting or using the Flare->Flarestar Feature.

**Comment by Grammernatzi** [comment]
Added with patch soon to be released.
