### ISSUE TITLE
mnk Perfect Balance

### ISSUE THREAD

**Issue by sz1523** [Grammernatzi/XIVComboPlugin#205]
I want a mode where I can use 1-2-3 like in AOE mode when using Perfect Balance and Single Target.
I want the forbidden chakra too

**Comment by athuy** [comment]
This is already an option
![image](https://github.com/user-attachments/assets/80dec7ad-6be7-4a76-97ca-8206ca0b11da)

**Comment by Grammernatzi** [comment]
I think what they are asking for is a single-target Perfect Balance solving combo. As I mentioned before, though, I don't plan on doing this for single target. The Forbidden Chakra thing is part of Expanded, though, so I can add that.

**Comment by Grammernatzi** [comment]
Added the forbidden chakra part with the patch soon to be released.
