### ISSUE TITLE
Quick Nock is replaced by Wide Volley before it is unlocked / useable.

### ISSUE THREAD

**Issue by Zeemgeem** [Grammernatzi/XIVComboPlugin#207]
![image](https://github.com/user-attachments/assets/4d364ea4-4e9d-4c5d-9a09-ef710516b320)

![image](https://github.com/user-attachments/assets/899b2971-7509-4ec6-a543-73b68b1cae7e)

This is a minor issue that only affects a handful of early ARR dungeons and guildhests, but it does still lead to needing to click off of hawk's eye if it procs one gcd, and you must swap to AOE on the next gcd.

**Comment by Grammernatzi** [comment]
Quickfixed, thank you for letting me know
