### ISSUE TITLE
Slow to update because can't use PC

### ISSUE THREAD

**Issue by Grammernatzi** [Grammernatzi/XIVComboPlugin#212]
Sorry if I've been delayed for 7.1; it happened right as I was in the middle of my move, so I can't access my desktop PC at the moment where I had everything saved. Or, rather, I have it, but it has no internet because this house currently has no wired internet and it has no wireless adapter and we're waiting for one to be delivered. I can't test if the plugin is broken or not, as a result, but once I am able to use my desktop I plan to update the plugin ASAP.

**Comment by 0kie** [comment]
I (locally on visual studio) cloned the repo and was able to make it work by editing the same stuff that was edited on MKhayle's branch, but  I have zero experience with github, never did a pull request or anything
I did not bump the version number so it would update once you updated, still 1.5.0.70

It currently has the same issue MKhayle's branch has with gauge jobs, which is a "dalamud not updated yet" issue

https://github.com/MKhayle/XIVComboExpanded/issues/459

I'm attaching a version of my edit already compiled, just need to replace on %appdata%\XIVLauncher\installedPlugins\XIVComboExpandedest\1.5.0.70
[XIVComboExpandedest.zip](https://github.com/user-attachments/files/17771102/XIVComboExpandedest.zip)

**Comment by Grammernatzi** [comment]
I should get the wireless adapter later today so I can probably get the work done then. So I can compare the code there and make the necessary adjustments. I'd prefer to test in-game before pushing a release, but that should be soon.

**Comment by sz1523** [comment]
I can't live without the tools you've created. I know it's hard, but I support you.

**Comment by Matuno** [comment]
Hah, just chiming in to say your work is missed ;) But take your time, life comes first.
Thanks in advance and thanks so far o/

**Comment by Grammernatzi** [comment]
Adapter didn't come in, but I do have a laptop that I am now able to transfer my development stuff to, so I should be able to update tonight.

**Comment by Grammernatzi** [comment]
Done, pushing now.
