### ISSUE TITLE
[Feature request] PLD - Don't immediately use up Atonement

### ISSUE THREAD

**Issue by Matuno** [Grammernatzi/XIVComboPlugin#214]
Tweak 181 is almost correct in that it will change the 1-2-3 combo to the Atonement combo when available. It is however probably preferable to have the same behaviour as 180 where it will wait until you are about to overwrite your stack of Diving Might to cast a free Holy Spirit.

Currently it's:

- Fast Blade > Riot Blade > Royal Authority
- [ Atonement > Supplication > Sepulchre ]
- Fast Blade > Riot Blade > [ Holy Spirit ] > Royal Authority
- [ Atonement > Supplication > Sepulchre ]
- Fast Blade > Riot Blade > [ Holy Spirit ] > Royal Authority

And what we'll probably want is:

- Fast Blade > Riot Blade > Royal Authority
- Fast Blade > Riot Blade
- [ Atonement > Supplication > Sepulchre ]
- [ Holy Spirit ] > Royal Authority
- Fast Blade > Riot Blade
- [ Atonement > Supplication > Sepulchre ]
- [ Holy Spirit ] > Royal Authority

And so on.

This allows more flexibility in delaying the Holy Spirit cast a little longer in the regular rotation. This is most notable in M4S during Witch Hunt where the timing can force you to disengage at that one moment where you would just have spent your Divine Might and can't be in range to hit another Royal Authority to gain new stacks. It also plays nicer with aligning your Atonement stack combo for raid buffs.

Thanks!

**Comment by Grammernatzi** [comment]
I can probably add this as an option; I will say that this is one of those cases where it might be just better to have a second button for Atonement rather than rely on automation lining up with what you want. I'll still go ahead and add that, though.

**Comment by Matuno** [comment]
> I can probably add this as an option; I will say that this is one of those cases where it might be just better to have a second button for Atonement rather than rely on automation lining up with what you want. I'll still go ahead and add that, though.

Thanks for getting back on this!

I agree, which is why I still have atonement and holy spirit as separate buttons since they need to be used up with precedence during burst windows. Problem is that the main combo will roll over into Atonement immediately and Atonement is the only button you can separately bind, effectively giving you two buttons that just stick to the Atonement combo.

I also realise I made one false assumption in all this: Holy Spirit cannot actually be delayed further by this, which was a main motivator in this request. On the other hand, it is still preferable to default to delaying Atonement to allow more flexibility in pushing it into burst windows.

During burst windows you'll typically fall back to separate binds for Atonement and Holy Spirit to spend them before the end of Fight or Flight anyway so your suggestion is also still very valid.

**Comment by Grammernatzi** [comment]
Added with newest version.
