### ISSUE TITLE
Empyreal Arrow turning into Pitch Perfect.

### ISSUE THREAD

**Issue by meltryllis-git** [Grammernatzi/XIVComboPlugin#215]
Hello! Thank you so much for adding [my  request](https://github.com/Grammernatzi/XIVComboPlugin/issues/210)!

Just a heads up though, I think there's an unintended interaction with "Empyreal Arrow to Sidewiner". My Empyreal Arrow button turns to Pitch Perfect whenever there's a stack.

**Comment by Grammernatzi** [comment]
Fixed in newest version.
