### ISSUE TITLE
[Bug][Bard][Ironjaws] Caustic bite no longer included

### ISSUE THREAD

**Issue by idecibel** [Grammernatzi/XIVComboPlugin#78]
hey, it seems like in the iron jaws feature something has broken recently. it now only ping between stormbite and iron jaws, and no longer does anything with caustic bite?

**Comment by Grammernatzi** [comment]
Only the secret has it. It should be enabled for everyone that enabled it before. I added a more legit option so that there was a less cheaty version people could use, but left the old one in (especially since it's in the original Expanded).

**Comment by idecibel** [comment]
Ah great - I probably hid the extra features and didnt remember anymore. This one indeed does the trick!
