### ISSUE TITLE
[PLD] Holy Circle/Holy spirit

### ISSUE THREAD

**Issue by idecibel** [Grammernatzi/XIVComboPlugin#79]
hey,

just wanted to take your temperature on this:

Under the effects of Requiescat would it make sense to replace the Prominence combo with Holy Circle?
Potentially also Holy SPirit to replace either the GB or RA combo as well.

**Comment by Grammernatzi** [comment]
It wouldn't be a good idea for holy spirit because the current PLD rotation is to use requiescat early, and then continue doing your combos. For Prominence combo, maybe?

**Comment by idecibel** [comment]
Yeah, i think prominence its safe, i guess if you're gonna aoe at that point no one is gonna **not** use holy circle.

**Comment by Grammernatzi** [comment]
Added the AoE version, don't think I could do the single target version, sadly. I try to make sure all of these features are compatible with current openers.
