### ISSUE TITLE
[RPR] Stalking and Swathing Feature+

### ISSUE THREAD

**Issue by idecibel** [Grammernatzi/XIVComboPlugin#80]
hey,

I like this feature, but since the gibbet and gallows enhanced version are on the same button, and this might sound stupid, in the heat of the battle I notice its easy for me to lose track of if the next one is the one with rear positional of the one with flank positional.

I think this was solved brilliantly with dragoon for the extended attacks. potentially something to look into for enhanced gibbet and gallows, in the sense that maybe a feature where the rear one replaces bloodstalk, and the flank one replaces slice combo or something.

what do you think?

**Comment by Grammernatzi** [comment]
I mean, can you not already do this with the Gibbets and Gallows Feature? I mostly added that option for people who didn't want to be able to hit Stalk/Swathe twice and thus end up wasting Soul Reaver.

**Comment by idecibel** [comment]
Ah yeah, you are indeed correct you can get this working with the options that currently exist! thanks!

**Comment by RandomSuggestions** [comment]
I think the only uncharted territory remaining with the Stalking and Swathing feature would be to let Gluttony in on the action. 

![image](https://user-images.githubusercontent.com/94084112/151465984-f84f8fc4-9c63-4650-9d5f-34a4f71f26d1.png)

There are three Voidsent Avatar buttons (Gluttony, Blood Stalk, Grim Swathe) and three Soul Reaver buttons (Gibbets, Gallows and Guillotine). If you let Gluttony pick up a Gibbet or a Gallows, you can then go on to condense every Reaper spender into those three bindings between the (Gluttony) Stalking and Swathing Feature, Combo Communio Feature, and the Lemure Feature. 

You're still always going to have Gluttony on your bars anyway to track that cooldown and there's very few instances where you're going to accidentally be hitting a Gluttony over anything else anyway.

**Comment by Grammernatzi** [comment]
> You're still always going to have Gluttony on your bars anyway to track that cooldown

I mean, personally, I just have it on a cooldown bar out of the way, but if someone would rather have this feature over the default one (which I use with Soul Slice), then, I guess if they really want it, they can have it.
