### ISSUE TITLE
[MNK] Suggestion for small change

### ISSUE THREAD

**Issue by idecibel** [Grammernatzi/XIVComboPlugin#81]
hello good sir,

I've played around a bit with the new MNK feature and it seems to cover everything and works really well. 
Being a sprout myself however, I have a suggestion which - admittedly is a L2P feature - but helps make the decision making process more visible at the cost of adding one extra button.

To elaborate a bit further: 
The current set up with having the 6 buttons converged into 2, is great to reduce the amounts of keybinds needed. However it has a disadvantage for newer players over the old "have all buttons on your toolbar" - which is the fact that the ones you can use light up. 

So as a noob, I have bound my twin snake buff on Shift+2. I don't need to know which form I am in now, and I don't need to know that I need to be in raptor form to use it. If it lights up, I look at my buff and depending on duration I can use it or not.

With the 2 button system - I never know if my 2 button is now dragon kick, twin snakes or demolish without processing: which stance am I in, and which stance is needed for the attack I want to do.  Or try to look at the icon and remember if this icon is the dot or the buff icon. This is fine for experienced players, but essentially complicates the job for beginners, making this button bloat-saver also an increase to complexity.

My suggestion is to add an optional feature, that can act as a potential intermediary step before people eventually becomes so familiar with it they can migrate to the current 2 button solution if wanted.

This option would require 2 enhancements:
1 - Only the current "true strike" feature is condensed into 1 button and it allows twin snakes and demolish not to be condensed, but stand alone on the hotbar (currently possible for demolish only)

2 - Under perfect balance the "true strike" button becomes Dragon Kick instead of Demolish as it does in the current feature.

This would make the "main" keybinds consist of 4 buttons including perfect balance:

![image](https://user-images.githubusercontent.com/24413091/150128099-57927d00-66c6-4888-9321-aa0140279149.png)

For the "standard flow" to get everything up, this would be a 1-2-3 combo:

![image](https://user-images.githubusercontent.com/24413091/150128239-019bb637-8002-483f-b270-e544a430fbf8.png)

For a pure DPS flow if dots and buffs are up, this would be a 1-1-1 combo:

![image](https://user-images.githubusercontent.com/24413091/150128352-24e7425a-7db1-4ad4-9c6c-c6995ddc6aba.png)

For the flow if the damage buff needs to be refreshed this would be a 1-2-1 combo:

![image](https://user-images.githubusercontent.com/24413091/150128470-cb6c2ec1-7329-4e93-9bf2-3b77c3fe8336.png)

For a DOT refresh, dot new target etc flow, this would be 1-1-3 combo:

![image](https://user-images.githubusercontent.com/24413091/150128577-75bd4e3e-b2d2-471e-9c65-d72f179c5385.png)

For a perfect balance combo, currently in place today, this would be a 4-4-4-4-4 combo:

![image](https://user-images.githubusercontent.com/24413091/150128743-932705d5-7346-46c1-9927-3998ab28aa64.png)

For the other perfect balance flow, this would be a 4-1-2-3-4 combo:

![image](https://user-images.githubusercontent.com/24413091/150128909-b6cbc1c2-9d8e-43b9-b34d-349d2dd92bfc.png)

This feature would combine the best of two worlds
- Remove some button bloat.
- Keep the simplicity of the original game by "I can now use the DOT attack" because the button is lit up.
- Keep the decision making process for what attack you want to use next.

I know you've done a lot of work on this - but hope you give this a thought as well! I tried to explain and make the argument to the best of my ability!

thanks

**Comment by idecibel** [comment]
yes thats about sums it up :) post became a wall of text indeed, but complicated monk stuff so wanted to try and be clear, at the end of the day im in any case happy that something was possible with monk at all!

**Comment by Grammernatzi** [comment]
Okay, I went ahead and added the options. Also added a Double Solar compatibility feature while I was at it. Tell me if the new additions work for you.

**Comment by idecibel** [comment]
it works perfectly, thanks a lot :)
i did realize indeed that my above thing didnt really take the double solar thing into consideration, but i find that whole thing a bit silly anyways, so im happy to just do it the normal way :)

**Comment by Grammernatzi** [comment]
I believe the double solar opener is barely much of a gain anyway so it's not too much of a big deal. I just figured I'd make sure that the combo could be used with it, since it didn't work with it before
