### ISSUE TITLE
/pcombo don't work

### ISSUE THREAD

**Issue by Konguo** [Grammernatzi/XIVComboPlugin#85]
/pcombo don't work

**Comment by Grammernatzi** [comment]
Do you have other XIVCombo plugins installed?

**Comment by Konguo** [comment]
no i don't

**Comment by Rileytaugor** [comment]
Are you sure you have the plugin enabled? Once you paste it in, you still
have to install it. I had similar "problem"

so 22. 1. 2022 v 17:38 odesílatel Konguo ***@***.***> napsal:

**Comment by Konguo** [comment]
found a fix. disabled the plugin and enabled it again. now it works
