### ISSUE TITLE
[GNB] Double Down Feature triggering on Solid Barrel Combo + Burst Strike Feature

### ISSUE THREAD

**Issue by Cadwgan** [Grammernatzi/XIVComboPlugin#87]
Unsure if this is intended, but when at 3 charges, about to overcap and the above 3 features are enabled, Solid Barrel displays Burst Strike as expected, but triggers Double Down when pressed.

**Comment by Grammernatzi** [comment]
This is a queueing bug and happens in the original plugin as well. Sadly, not much can be done, but at least if you time your rotation well enough, this shouldn't happen outside of No Mercy.

**Comment by Cadwgan** [comment]
Shame, for now I have a workaround using ReAction if others report this issue and don't mind using another plugin:
![image](https://user-images.githubusercontent.com/8039241/151137996-38502818-acdf-4e48-9ad8-e4774d9bfced.png)

Just need to disable Double Down feature and drop said action in place of Burst Strike.

**Comment by Grammernatzi** [comment]
ReAction works without using the default icon replacer, so that thankfully doesn't run into the same issue. Maybe Daemitus could look into the code for it to see if there's a way he can use it to prevent this sort of problem.
