### ISSUE TITLE
[Suggestion] MNK Perfect Balance -> Masterful Blitz improvement

### ISSUE THREAD

**Issue by lgdsgoalieguy** [Grammernatzi/XIVComboPlugin#89]
My suggestion is to make Perfect Balance swap to Blitz while under the effect of PB, not just after a blitz is available. This will prevent accidental double PB, wasting a blitz.

**Comment by Grammernatzi** [comment]
Probably a good idea. I'll look into it.

**Comment by Grammernatzi** [comment]
Fixed in latest version.

**Comment by lgdsgoalieguy** [comment]
This doesn't appear to be fixed. At least with just the PB -> Blitz enabled

**Comment by Grammernatzi** [comment]
It is a new option, you just need to enable the lockout feature.

**Comment by lgdsgoalieguy** [comment]
Am I blind? I'm not seeing that in the MNK options.

**Comment by Grammernatzi** [comment]
It should be a child option of the Perfect Balance feature called Perfect Balance Feature: Lockout

**Comment by lgdsgoalieguy** [comment]
![image](https://user-images.githubusercontent.com/15915452/152707218-409dd9ac-654f-4a7a-8999-559511e8dd9a.png)

I'm still not seeing it, I'd expect I should see a dropdown arrow or something.

**Comment by Grammernatzi** [comment]
Your version is not the current version. I can tell because it's missing
the cooldown disclaimer at the top. Are you using the right repository?

**Comment by lgdsgoalieguy** [comment]
Alright we're in business now. I had to disable and reenable the plugin. Thanks for the help!

**Comment by Grammernatzi** [comment]
No problem. Have a good evening/day/etc!
