### ISSUE TITLE
Kassatsu to Trick - not swapping between 45-49

### ISSUE THREAD

**Issue by DJFarr** [Grammernatzi/XIVComboPlugin#90]
Hi,

I was playing around with Kassatsu to Trick, and noticed that it explicitly swaps to Trick  when Suiton is up + Kassatsu is on cooldown, OR Hidden is up.
This works fine when Hidden, but has an issue between 45-49 where players can use Suiton but no Kassatsu.
In this range, It doesn't swap to Trick while Suiton is up, because Kassatsu cannot be on cooldown.

Its technically a feature request I suppose, as it already does exactly what its description says, but I feel that this would be a bit more usable, because in its current state the feature does not allow you to use Trick inside combat for a 5 level range where it is possible to do so.

Should be an easy enough change, from:
```
if (actionID == NIN.Kassatsu)
{
    if ((HasEffect(NIN.Buffs.Suiton) && !IsActionOffCooldown(NIN.Kassatsu)) || HasEffect(NIN.Buffs.Hidden))
        return NIN.TrickAttack;
}

return actionID;
```
to 
```
if (actionID == NIN.Kassatsu)
{
    if ((HasEffect(NIN.Buffs.Suiton) && (!IsActionOffCooldown(NIN.Kassatsu) || level < NIN.Levels.Kassatsu)) || HasEffect(NIN.Buffs.Hidden))
        return NIN.TrickAttack;
}

return actionID;
```

Thanks, loving the combos!

**Comment by Grammernatzi** [comment]
Admittedly I just ended up using DwaD/Assassinate to Trick instead, since that was a lot less janky to use. But I will look into this and see if I can fix it.

**Comment by Grammernatzi** [comment]
Fixed in latest version.
