### ISSUE TITLE
Issue vs PR?

### ISSUE THREAD

**Issue by DJFarr** [Grammernatzi/XIVComboPlugin#92]
Hi,

Apologies for making a whole Issue to ask a question, not sure how else to reach you.

As for requesting features, I wanted to ask what your preferred flow was, if I had already tested some fixes on my end?
i.e. I have this commit to my own fork for testing purposes regarding MNK level-sync issues:
[https://github.com/DJFarr/XIVComboPlugin/commit/73de968ca10d18da8d022cbb38d797c973f14d21](https://github.com/DJFarr/XIVComboPlugin/commit/73de968ca10d18da8d022cbb38d797c973f14d21) 

> MNK level sync issues with the Simple Combos
Fixed Masterful Blitz so that it didn't overwrite the base combos immediately if below level 60.
Updated Dragon Kick Simple combo so that players can spam click it to refresh cooldowns and it will still cycle through the Forms at low levels.

Would you prefer if I had just directly submitted a PR out of nowhere, or would you like to check the changes made and implement them in your own way?

Thanks

**Comment by Grammernatzi** [comment]
I just fixed the first one and am pushing it; the second one, I left it as-is because I figured the Dragon Kick combo didn't need to sync to True Strike/Snap Punch/Bootshine (as you'd still be doing about the same muscle memory anyway as at higher levels, and that way you wouldn't have weird muscle memory built from leveling or synced content), but if you want it as an option, I can probably add it as such.

**Comment by DJFarr** [comment]
Awesome, great to hear,
I did actually find that one myself today as well, thought its not quite a 1 click setup as it does require the Monk Bootshine feature (Bootshine/DragonKick leaden fist swap-out).
I'll be trying it out a bit more soon.

I think I'll be avoiding the Monk Combos (Experimental) for now as it was just too hard to wrap my head around the combos without seeing an example of button layout and rotation using it. I got close but couldnt get it.

Luckily though the above simple combo you posted looks like it'll suit my style a bit better

**Comment by Grammernatzi** [comment]
The experimental monk combos are basically created as the way to save the most buttons possible, regardless of comfort. I created the simple ones after for combos that were more comfortable but didn't save as many buttons. Though, with the setup I have, only one less button is saved, so it's not bad at all.

**Comment by DJFarr** [comment]
Ahh i see, The impression i had from reading the descriptions was that the Experimental combo was the current one being worked on, as a replacement for all the others. Interesting to know its almost the opposite, haha.

And that suggestion sounds pretty good.

I had thought about suggesting some sort of "Lazy Mans Solar combo" where, in PB, the Dragon Kick combo would just rotate through DK(or Bootshine with the option) / Twin Snakes / Demolish, so  you could get all 3 on the one button (similar to how the AoE combos handle it), however i know in end-game combos the order of the 3 changes, and I couldn't be bothered calculating the best default order.

**Comment by Grammernatzi** [comment]
Eh, I think for the Solar Combo, you often want to change the order of Demolish/Twin Snakes/Opo-Opo due to what needs refreshing first. So I think it's better to just leave it as-is. I did implement the Twin Snakes option for the Dragon Kick Combo, though. It does look a little funky, but it also does play pretty nicely.

**Comment by DJFarr** [comment]
Fair enough, it was just a thought I had and I only just unlocked Blitz today so I can't really claim experience there.

I'll look forward to trying out the twin snake combo tomorrow
