### ISSUE TITLE
MNK Bootshine Feature by itself causes Bootshine use in Raptor form.

### ISSUE THREAD

**Issue by DJFarr** [Grammernatzi/XIVComboPlugin#93]
Testing Bootshine Feature (Dragon Kick <-> Bootshine when you have Leaden Fist) by itself (without either Simple Combo in use) is a somewhat valid use-case.

The code for the feature itself does not contain checks for OpoOpo || Formless fist || Perfect Balance, as those checks are mostly done inside the other combos. Understandable how that happened as it would be rare to see this feature in use by itself.

Anyway if you're testing out the current DragonKick meme rotation, Using just Dragonkick until buffs are about to run out, then using DK in Raptor form should use DK, not Bootshine.

```
    internal class MnkBootshineFeature : CustomCombo
    {
        protected override CustomComboPreset Preset => CustomComboPreset.MonkBootshineFeature;

        protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
        {
            if (actionID == MNK.DragonKick)
            {
                if (HasEffect(MNK.Buffs.LeadenFist) && (HasEffect(MNK.Buffs.OpoOpoForm) || HasEffect(MNK.Buffs.FormlessFist) || HasEffect(MNK.Buffs.PerfectBalance)))
                    return MNK.Bootshine;

                if (level < MNK.Levels.DragonKick)
                    return MNK.Bootshine;
            }

            return actionID;
        }
    }

```

**Comment by Grammernatzi** [comment]
I am unfamiliar with the 'Dragon Kick meme rotation', but, fair. I can easily implement this since there's no real downsides. It'll be in the next version.

**Comment by DJFarr** [comment]
Thanks,

It's all over the Balance discord for the last day or so. replace all uses of True Strike and Snap Punch with Dragon Kick, and just refresh buffs/dots as necessary (therefore use Bootshine every 2nd dot cycle). it results in about a 5% dps loss but is braindead and a guy got a 99 parse with it

**Comment by Grammernatzi** [comment]
I tried it and it was closer to a 2.8% DPS loss myself (from 7300 to 7100 on dummy). It was enough that I couldn't beat the p4s dummy with it, just barely getting close, whereas I could with the normal rotation, but still surprisingly similar. Then again, my normal rotation isn't as optimal as it could be, so maybe an optimal super refined rotation is 5% more.
