### ISSUE TITLE
Suggestion: Swap Cast with Gig for Spearfishing nodes

### ISSUE THREAD

**Issue by lResume** [Grammernatzi/XIVComboPlugin#95]
Since the two are mutually exclusive, I find myself swapping hotbars to keep my keybinds easy to use. I'd love to see this; maybe it'll open the way for other fishing improvements.

**Comment by Grammernatzi** [comment]
I might pull the stuff Daemitus has over, I think he's figured some of it out. I never really considered it a priority because, well, macros exist and do the job just fine, but if he has it I'll dump it in.

**Comment by Grammernatzi** [comment]
Went ahead and added his stuff; for future things, though, generally I prefer stuff that can't already be replicated with macros, which, for gatherers, isn't too much. Though, I guess it does save on macro space, and looks nicer. I'll mainly just add whatever Daemitus does.
