### ISSUE TITLE
Dragoon - Claws and Fangs/Wheeling Trust

### ISSUE THREAD

**Issue by Laiev** [Grammernatzi/XIVComboPlugin#96]
Hey, would it possible to do something you did for Reaper on Gibbet and Gallows, but for Dragoon on Claws and Fangs becoming Wheeling Trust?

Like one button for both

**Comment by Grammernatzi** [comment]
The combos already do this, don't they? Unless you'd prefer to not have the combos enabled, which I can understand.

**Comment by Laiev** [comment]
Ya, exactly, I prefer not to have the combos enabled

**Comment by Grammernatzi** [comment]
I'll look into it when I get back into development, then; at the moment, been preoccupied with Elden Ring.

**Comment by Grammernatzi** [comment]
On that note, are there any other features you might want for uncombo'd needs? I thought of maybe Full Thrust turning into Chaos Thrust after using Disembowel, or both Full/Chaos turning into Fang/Wheeling, without having to enable the combos. Just stuff I was brainstorming, I've just been wanting to figure out more features that still let you save buttons without resorting to one-button combos.

**Comment by Laiev** [comment]
What you did for Reaper is one of the perfect examples for me. Skills that use positional and are not part of a combo-action-like (like Reaper Gibbet/Gallows, Dragoon Claws and Fangs/Wheeling Trust) for one button (so you just change your position and still use same button) are perfect for me, I dislike combo 1-2-3 into one button, and I prefer the utility of other keybinds.

Other one for Dragoon that I think about too, is Dragon Sight and/or Geirskogul/Nastrond become Wyrmwind Trust (when available),

**Comment by Grammernatzi** [comment]
I feel that both of those could possibly conflict in a rotation; I think the current Raiden Thrust to Wyrmwind Thrust works well enough in an uncombo'd situation, as you never want to use the former before using the latter. With that said, I'll try and work the Fang/Wheeling thing in later, of course.

**Comment by Grammernatzi** [comment]
Added in latest version.
