### ISSUE TITLE
(Bug) Chaos Thrust is not getting replaced by Wheeling Thrust

### ISSUE THREAD

**Issue by faultlline** [Grammernatzi/XIVComboPlugin#97]
I'm lvl70 and testing on a dummy Chaos and Full Thrust aren't replaced by Wheeling Thrust when using the Chaos Thrust combo.
It goes like this: True Thrust > Disembowel > Chaos Thrust > resets to True Thrust.
With Full Thrust it works as intended: True Trust > Vorpal Thrust > Full Thrust > Chaos and Full Thrust buttons become Fang and Claw > Chaos and Full Thrust buttons become Wheeling Thrust > resets back to True Thrust.
This is what I have enabled:
![image](https://user-images.githubusercontent.com/97929169/156770883-2c3d8881-d199-48cb-8c83-9cb191d30d73.png)
I can work around the bug by using the Wheeling Thrust/Fang and Claw option but it's a little bit inconvenient.

**Comment by Grammernatzi** [comment]
Fixed in latest version.
