### ISSUE TITLE
Chaos Thrust is not getting replaced by Wheeling Thrust #2

### ISSUE THREAD

**Issue by faultlline** [Grammernatzi/XIVComboPlugin#98]
Sorry to bother again but the bug is still happening, this time while synched down to lvl60.
It goes: True>Disembowel>Chaos>True again.
Full Thrust combo works fine: True>Vorpal>Full>Fang and Claw>back to True
Wheeling Thrust/Fang and Claw option also still works to circumvent this minor problem.

**Comment by Grammernatzi** [comment]
I will give it another look, that's odd. Maybe something weird is going on
with level sync.

**Comment by Grammernatzi** [comment]
While I'm working on it, it's worth noting that the Full Thrust to Chaos Thrust feature fixes this issue since it disables the cosmetic combo thing, and shouldn't mess with your rotation at all (same inputs are still used, full thrust combo will just change to chaos thrust combo if you ever use disembowel in a combo). So that's a temporary solution for now that works for all levels.

**Comment by Grammernatzi** [comment]
![image](https://user-images.githubusercontent.com/869037/156945821-0044febd-6522-46a8-a3df-a6cf50a1f6fc.png)
It seems to be working fine for me? That's odd; I synced myself to 60 and everything. Maybe try installing/reinstalling?

**Comment by faultlline** [comment]
It's inconsistent now, sometimes it works fine but most of the time it doesn't
![image](https://user-images.githubusercontent.com/97929169/156952142-84630b73-e8fe-4830-aabb-525b81d24e41.png)
The first True Thrust on my bar should be Wheeling.
![image](https://user-images.githubusercontent.com/97929169/156953089-c130532b-765e-4fbe-ba15-b0ac08bea653.png)
Tried reinstalling plugin, restarting game, putting Chaos Thrust on hotbar, putting Chaotic Spring(which I don't have yet so it's replaced by Chaos Thrust) on hotbar, none of those worked.

**Comment by Grammernatzi** [comment]
Very weird; not sure what's causing it, then. But for now, you can enable the Full Thrust to Chaos Thrust option and it SHOULD work fine without causing any issues? I'll try to troubleshoot why it's happening.

**Comment by Grammernatzi** [comment]
I think I may have fixed it? Got to test it more, first, but pushed the change anyway.

**Comment by faultlline** [comment]
Works perfectly now. Thank you very much for looking into it!
