### ISSUE TITLE
Wheeling Thrust and Fang and Claw issue.

### ISSUE THREAD

**Issue by Zeemgeem** [Grammernatzi/XIVComboPlugin#99]

**Comment by Zeemgeem** [comment]
Before the update, Wheeling Thrust and Fang and Claw would occupy both combos as they came up, but now only occupy the slot of the last combo used. I don't like this behaviour as I am disabled and struggle to hit my Chaos Thrust bind this many times in succession. Can we have an option to reverse this?

**Comment by Zeemgeem** [comment]
![image](https://user-images.githubusercontent.com/83545214/157597419-87f758b0-e08f-414c-94f1-80d7d15cbfd4.png) It looks like this. In this instance I just used Chaos Thrust, and only the Chaos Thrust combo is updated.

**Comment by Zeemgeem** [comment]
Upon further testing, enabling Full Thrust to Chaos Thrust resolves my problem, though Chaos Thrust does not become Full thrust when Full Thrust is available while using this setting, which seems an oversight of it's own.

**Comment by Grammernatzi** [comment]
Yes, Full Thrust to Chaos Thrust fixes this. I probably should put this in its description. If you want the opposite behavior, I suppose I could do that? But the idea was that you had a single combo and just hit disembowel to change it. It's what I'm currently using.

**Comment by Grammernatzi** [comment]
I went ahead and just made the cosmetic change optional, so this should be fixed.
